### ISSUE TITLE
I can not log in.

### ISSUE THREAD

**Issue by GibranLara** [ipassynk/angular-springboot-jwt#1]
Hello,

I'm having trouble trying to test the application together. I have tried the backend project separately and does what the original author points out. Then I executed your frontend as indicated, but when trying to log in it throws the error "User or password is incorrect".

When I give Sing In I get the following error in console in the browser.
![image](https://user-images.githubusercontent.com/22408615/29228979-a439ca4e-7ea1-11e7-9349-2ba10a94db77.png)

I hope and you can help me, please, thank you.

**Comment by corlaez** [comment]
I found this [answer by jingglang](https://github.com/angular/angular/issues/17572#issuecomment-309229619) and I decided to change the angular version to 4.1.3 (except the compiler which I set on 4.4.6)- However now the ng serve doesn't serve the page properly and i get an error: Uncaught TypeError: jit_val_0 is not a function
    at eval (ng:///AppModule/module.ngfactory.js:3)

**Comment by santteegt** [comment]
Fixes to this issue were sent on pull #3

**Comment by HunterGerlach** [comment]
@GibranLara 
You're not able to login because the application isn't redirecting your requests (from localhost port 4200) to the backend server which is being served on a different port (8080). Try this when serving your application...

`ng serve --proxy-conf proxy.conf.json`

**Comment by mahdiraddadi** [comment]
thanks @HunterGerlach , I like the way of using a proxy

**Comment by GibranLara** [comment]
@HunterGerlach thank you so much!
