### ISSUE TITLE
Angular 5 Support

### ISSUE THREAD

**Issue by beyazkemal** [ipassynk/angular-springboot-jwt#4]
Hi, 
how can we update the repo for Angular 5 support?

Thanks.

**Comment by ipassynk** [comment]
I will be happy to accept PR. Thanks

**Comment by beyazkemal** [comment]
This article very helpful for me: https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8
